phaazon/luminance-rs

src/pipeline.rs
src/shader/program.rs
src/texture.rs
src/vertex.rs

Small readability things and idiosyncracies (like using slices instead of `&Vec`s in function arguments).

fixed some clippy warnings

---

README.md

Adds links to docs.rs, which hosts online documentation for crates on crates.io.
This lowers the barrier for interested users to peruse the documentation.
Honestly a lot of projects I access docs.rs from their README anyways. :)

Add references to online documentation.

---

luminance/src/pixel.rs

I'm currently playing with blur algorithms and needed a floating point format which is less bulky than the RGB32F currently available in Luminance. Switching to R11FG11FB10F from RGB32F let me increase my texture sampling unit throughput from 45% utilization to 70%, resulting in an overall speedup of ~2x. I figured I would share the goodies.

Add support for the R11FG11FB10F pixel format

---

luminance/examples/06-texture/src/main.rs
luminance/examples/07-offscreen/src/main.rs
luminance/src/pipeline.rs
luminance/src/pixel.rs

PR version of my prototype. Nothing has changed in the code. Copy/pasting my response to commit comments for visibility.
> The thing I'm not convinced is correct with this change is my removal of the `Texture` from the `BoundTexture` phantomtype. Glancing through the implementation of `BoundTexture` it doesn't look like we need the `Texture` to be there explicitly, but I'm not super clear on what invariants that `PhantomType` was trying to enforce -- my knowledge of unsafe Rust is relatively weak at this time. I suppose I should turn this into a proper PR to continue discussion.
Fixes #107

All sampler uniforms to be generic over texture format

---

.travis.yml

We’re now testing everything (even documentation). Also, removes the
verbose output. I’ve never needed that and it should be easy to rebuild
a failed job in verbose if needed (but I really doubt we will ever).
> This is going to fail at the first time because some fix for the doc is present in another PR. I’ll rebase when it’s okay to.

Enhance the CI testing.

---

luminance/src/lib.rs
luminance/src/pipeline.rs
luminance/src/state.rs
luminance/src/tess.rs
luminance/src/vertex_restart.rs

Using `u32` all the time is massively wasteful for many workloads, since we rarely have meshes with more than 65535 vertexes (so we can get away with `u16`s).  GL also supports `u8` index buffers, which are handy for very small meshes, like the full-screen triangles often used for lots of post-processing effects, so we add support for those as well since it's easy enough to do. We may also want to add support for `()` as an "index buffer type" for directly rendered meshes, as right now the user needs to arbitrarily pick a type (from `u8`, `u16`, or `u32`) to fill the `Tess` type parameter

[RFC] Support different types for the index buffer.

---

luminance/examples/06-texture/src/main.rs

Fix a typo

---

luminance-glfw/Cargo.toml
luminance-glfw/src/surface.rs
luminance-windowing/src/lib.rs
luminance/Cargo.toml
luminance/examples/06-texture/Cargo.toml

This also removes the default features on glfw, these can be enabled by a user of this library down the road if they need them.

Update dependencies, and fix warnings

---

luminance-glfw/src/surface.rs
luminance-windowing/src/lib.rs

Set glfw window hint Samples from WindowOpt.
By default this is None and behavior is unchanged.

Add samples to WindowOpt - #91

---

luminance-glfw/Cargo.toml

This gets rid of semver 0.2.3 and thus of nom 1.2.4.

Update glfw to 0.31

---

luminance/examples/06-texture.rs
luminance/src/pixel.rs

These four formats read from `GL_UNSIGNED_BYTE` and are accessed as `sampler2D` (float) in shaders.

Implement unsigned byte formats

---

luminance/src/pixel.rs
luminance/src/texture.rs

They got replaced by saner approaches and even safe ones!

Remove std::mem::uninitialized references. #181

---

bin/viewer/src/main.rs
luminance-derive/src/vertex.rs
luminance/examples/01-hello-world.rs

Add ::new methods for user vertex types, so that they don’t have to do it.

---

luminance-glutin/src/lib.rs

This enum is used in `glutin::WindowEvent::MouseInput`, but `luminance-glutin` does not re-rexport it.

Re-export `glutin::MouseButton` in `luminance-glutin`

---

luminance-gl/src/shader/program.rs
luminance/src/context.rs
luminance/src/shader/program2.rs

Because some implementation will / might require some branching,
and currently, Rust doesn’t have match in const items (it’ll arrive but
not now), we cannot use associated consts for this.

(pr) Revert Uniformable::TY to Uniformable::ty().

---

luminance-examples/src/hello-world-glutin.rs

Multiple reason to change:
* if you put `*control_flow = ControlFlow::Poll` at the beginning of the loop it will be called everytime the loop is it
* by default the control_flow is in Poll mode [glutin doc ControlFlow](https://docs.rs/glutin/0.23.0/glutin/event_loop/enum.ControlFlow.html)
* Poll usage is for extensive used of redraw, like in video game, but this example only redraw when a keyboard input is hit, so `ControlFlow::Wait` is the recommended way to handle this kind of event loop (same link as above)
As describe in winit examples, using `Event::NewEvents(StartCause::Init)` is the recommended way to handle init configuration.

Moving from ControlFlow::Poll to ControlFlow::Wait

---

luminance-gl/src/gl33/buffer.rs
luminance-gl/src/gl33/pipeline.rs
luminance-gl/src/gl33/tess.rs
luminance/src/backend/buffer.rs
luminance/src/backend/pipeline.rs
luminance/src/buffer.rs
luminance/src/pipeline.rs

This is currently needed for #232, but it will be useful for pretty much
any backend too.

Make the backend interface of buffers Copy friendly.

---

luminance-examples/src/attributeless.rs
luminance-examples/src/displacement-map.rs
luminance-examples/src/dynamic-uniform-interface.rs
luminance-examples/src/hello-world-glutin.rs
luminance-examples/src/hello-world.rs
luminance-examples/src/offscreen.rs
luminance-examples/src/query-texture-texels.rs
luminance-examples/src/render-state.rs
luminance-examples/src/shader-uniforms-adapt.rs
luminance-examples/src/shader-uniforms.rs
luminance-examples/src/sliced-tess.rs
luminance-examples/src/texture.rs
luminance-examples/src/vertex-instancing.rs
luminance/src/context.rs
luminance/src/shader.rs

This change set provides a nicer user experience that reduces the number of type variables they have to deal with, passing objects and importing types for several types (among shaders and tessellations).
The PR is made out of two parts:
- Two commits that update the API (API hygiene).
- One commit that updates the examples.

API simplification

---

luminance-derive/src/attrib.rs
luminance-derive/src/semantics.rs
luminance-derive/src/uniform_interface.rs
luminance-derive/src/vertex.rs
luminance-gl/src/gl33/state.rs
luminance-glfw/src/lib.rs
luminance-glutin/src/lib.rs
luminance/src/buffer.rs
luminance/src/framebuffer.rs
luminance/src/pipeline.rs
luminance/src/shader.rs
luminance/src/tess.rs
luminance/src/texture.rs

A couple of notes:
* I didn't try to necessarily improve the error text at all. In the few places where I had to actually add text, it's relatively barebones, but I can make improvements there if you want.
* `luminance-derive::SemanticsImplError::AttributeErrors` is a vector of errors, so I use the first one (arbitrarily) as a source.
* I implemented `error::Error` for `ProgramWarning`, despite it not quite being an error.

implement std::error::Error for errors in all crates

---

luminance-gl/src/gl33.rs
luminance-gl/src/gl33/state.rs

Implements #333.
Exposes GLState and adds several `reset` functions to it that allow invalidating the values cached in the state. Purpose of this is to enable using luminance together with other libraries that use OpenGL.

Resetting cached GL state

---

.github/workflows/ci.yaml
Cargo.toml
luminance-sdl2/CHANGELOG.md
luminance-sdl2/Cargo.toml
luminance-sdl2/LICENSE
luminance-sdl2/README.md
luminance-sdl2/src/lib.rs

I've been using luminance with sdl2 for a while now and I think it works great. I thought I'd share what I built, but I didn't realize you had this massive 0.40 rewrite on the way.
I rewrote the Sdl2Surface to my best understanding of the new architecture, but I haven't ported my game to 0.40 yet, so I haven't really tested this incarnation of the surface. I figured I might as well open the PR now, and mark it as ready once I've confirmed it still works.

Add luminance-sdl2 backend.

---

luminance-gl/src/gl33/pipeline.rs
luminance-gl/src/gl33/state.rs
luminance/src/blending.rs
luminance/src/render_state.rs

There were some choices to be made in the API. I added distinct functions for the 'separate' blending functionality, which has the benefits of (1) compatibility with existing code and (2) matching the OpenGL API. Another choice would be to only expose the 'separate' versions.

Support separate rgb/alpha for blending equations and factors. #296

---

luminance-sdl2/Cargo.toml

That feature allows to enable the sdl2/bundled feature. Enabled by
default.

Add luminance-sdl2’s "bundled" feature. #371

---

luminance-gl/src/gl33/pipeline.rs
luminance-gl/src/gl33/state.rs

Notice the `glActiveTexture`, which are texture unit activations — completely useless here.

Enhance texture unit caching to prevent switching texture units when no texture bind would occur

---

luminance-gl/src/gl33/shader.rs

Since the Program::link() takes a &self, the Program’s Drop impl will be
called when we stop using it, and then will be dropped at that moment.
Without this current commit, the Drop might create a double-free.

[gl33] Fix potential double-free on the GPU when a Program doesn’t link.

---

luminance-webgl/src/webgl2/texture.rs

Hey @phaazon!
How's it going?  Here is a PR for #364

Return TextureError::UnsupportedPixelFormat if the WebGL Pixel Format does not exist. #364

---

README.md

Add luminance-glyph is in the list of dependent crates on the front README.

---

luminance-gl/src/gl33/tess.rs
luminance-webgl/src/webgl2/tess.rs

Fix for #392.
Resolve a compile error when calling Tess:vertices() or Tess:instances(), due to a typo in the TessVertexData bound of the *SliceBackend implementations.

Fix Interleaved/Deinterleaved typos in VertexSliceBackend/InstanceSliceBackend implementations

---

luminance-webgl/src/webgl2.rs
luminance-webgl/src/webgl2/array_buffer.rs
luminance-webgl/src/webgl2/pipeline.rs
luminance-webgl/src/webgl2/texture.rs

Add a **public** trait `luminance_webgl::webgl2::IntoArrayBuffer`, which can convert a slice of texels into a `js_sys::*ArrayBuffer` (e.g. `Uint8ArrayBuffer`).  
This allows TextureBackend::upload_texels to provide type-safe webgl array buffers, where P::RawEncoding and P::Encoding implement IntoArrayBuffer.  As mentioned in #385, this fixes texture uploads for floating-point types, as well as some WebGL warnings.  I tested the fix with RGBA uploads of `&[u8]`, `&[f32]`, and `&[(f32, f32, f32, f32)]`.
I also noticed that `create_texture_2d_storage` can be simplified - as `WebGl2RenderingContext` provides a `tex_storage_2d` method that creates all the mipmaps in a single call.  I made a similar change for `create_texture_3d_storage`, but left the cubemap function alone.
I think there are a …

Implement type-safe texture uploads for f32, u8-32, and i8-32

---

luminance-gl/src/gl33/buffer.rs
luminance-webgl/src/webgl2/buffer.rs

Resolves #397.
These implementations initialize pointer as `self.len`, but they should be copying `self.ptr`.

Fix a pointer bug in the BufferSlice/BufferSliceMut transmute implementations

---

luminance-examples/src/hello-world-glutin.rs
luminance-glutin/src/lib.rs

Also, rename the `new` and `from_builders` `new_gl33` and
`new_gl33_from_builders`.
Relates to #401.

[luminance-glutin, luminance-examples] Exposes EventLoop when creating the surface.

---

luminance-front/src/tess.rs

This resolves the discrepancy of `luminance-front` from `luminance` by specifying default concrete types for the generic type parameters of `Tess` and `TessBuilder`.
https://github.com/phaazon/luminance-rs/blob/65a31ab6761ca74dfcf5f13ac343fb2253268e20/luminance/src/tess.rs#L893
https://github.com/phaazon/luminance-rs/blob/65a31ab6761ca74dfcf5f13ac343fb2253268e20/luminance-front/src/tess.rs#L9
https://github.com/phaazon/luminance-rs/blob/65a31ab6761ca74dfcf5f13ac343fb2253268e20/luminance/src/tess.rs#L517
https://github.com/phaazon/luminance-rs/blob/65a31ab6761ca74dfcf5f13ac343fb2253268e20/luminance-front/src/tess.rs#L8

Preserve the default type for Tess and TessBuilder.

---

luminance/src/pipeline.rs
luminance/src/shader.rs
luminance/src/tess.rs
luminance/src/texture.rs

This PR adds `PartialEq` and `Eq` derives to public enums where applicable.
The `luminance-glfw` crate also had some enums that didn't have this derive, but I wasn't able to build the crate (due to not having glfw installed on my machine) in order to do a `cargo check`, so I didn't add any derives in case one of the variants doesn't implement it.
I haven't opened an issue, as this is a relatively simple change that doesn't affect much, I believe.

[luminance] Add `PartialEq` and `Eq` derives to applicable public enums.

---

integration-tests/desktop/fixtures/src/main.rs
integration-tests/desktop/fixtures/src/scissor.rs
integration-tests/desktop/fixtures/src/tess_no_data.rs
luminance-gl/src/gl33/pipeline.rs
luminance-gl/src/gl33/state.rs
luminance-webgl/src/webgl2/pipeline.rs
luminance-webgl/src/webgl2/state.rs
luminance/src/lib.rs
luminance/src/pipeline.rs
luminance/src/render_state.rs
luminance/src/scissor.rs

This PR allows the user to apply a scissor region to drawn geometry using gl::Scissor internally to produce effects like the following.

WIP: Add ability to scissor geometry via RenderState

---

integration-tests/desktop/src/main.rs
integration-tests/desktop/src/manually_drop_framebuffer.rs

On Archlinux, I don’t reproduce with the following setup:
```toml
[dependencies]
image = "0.23"
luminance = "0.40"
luminance-derive = "0.6"
luminance-glfw = "0.13"
luminance-glutin = "0.10"
luminance-windowing = "0.9"
glfw = "0.39"
glutin = "0.24"
```
```
λ uname -a
Linux orchid 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64 GNU/Linux
λ glxinfo | rg OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 2070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.82
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 440.82
OpenGL shading language version string: …
```

Add a fixture to demonstrate #360

---

luminance-sdl2/src/lib.rs

There was previously no way of getting a mutable borrow of the underlying window, preventing use of mutating methods such as `Window::hide`, `Window::set_title` and others.

Add luminance_sdl2::GL33Surface::window_mut.

---

luminance-examples/src/displacement-map.rs
luminance-examples/src/skybox.rs
luminance-examples/src/texture.rs

The method `DynamicImage#to_rgb()` is deprecated; this PR updates invocation to the current method `to_rgb8()`.

Update calls to deprecated method `to_rgb()`

---

luminance-examples/Cargo.toml
luminance-examples/src/texture_resize.rs
luminance-gl/src/gl33/texture.rs
luminance-webgl/src/webgl2/texture.rs
luminance/src/backend/texture.rs
luminance/src/texture.rs

Both Encoding and RawEncoding are supported. The interface takes the
texels (and whether we should generate the mipmaps), and serves as a
proof of concept of the new interface to create textures.
Relates to #473.

Implement texture resizing.

---

luminance-glfw/CHANGELOG.md
luminance-glfw/src/lib.rs
luminance-windowing/CHANGELOG.md
luminance-windowing/src/lib.rs

This type is getting moved out as `luminance` is not about providing a
windowing solution. `luminance-glfw`, `luminance-glutin`,
`luminance-sdl2` and `luminance-web-sys` (so far) are just crates to
_ease_ creating the environment to work with those crates.
Relates to #342.

Remove `CursorMode` from `luminance-glfw`.

---

luminance-gl/src/gl33/texture.rs
luminance-webgl/src/webgl2/texture.rs
luminance/CHANGELOG.md
luminance/src/pixel.rs

Use arrays instead of tuples for pixel encoding.

---

luminance-examples/Cargo.toml
luminance-examples/src/query-info.rs
luminance-front/src/lib.rs
luminance-front/src/query.rs
luminance-gl/src/gl33.rs
luminance-gl/src/gl33/query.rs
luminance-gl/src/gl33/state.rs
luminance-webgl/src/webgl2.rs
luminance-webgl/src/webgl2/query.rs
luminance-webgl/src/webgl2/state.rs
luminance/src/backend.rs
luminance/src/backend/query.rs
luminance/src/context.rs
luminance/src/lib.rs
luminance/src/query.rs

This commit introduces the very beginning of the Query API, that will be
used to implement various queries on the backend to provide versions,
names and capabilities of the GPU / hardware.
This commit introduces the main API along with:
- The backend “author” (vendor, company, etc.).
- The backend name.
- The backend version.
- The backend shading language version.
This commit holds both the implementations for the OpenGL 3.3 and WebGL2
backends.
Relates to #492.

Add premises of the Query API.

---

luminance-derive/src/lib.rs
luminance-derive/src/vertex.rs

Hi! I was messing around with this crate and didn't realize that fields of a struct deriving `Vertex` needed to have different types (ex `struct Vertex { pos: VertexPosition, tex_coords: VertexPosition }` vs `struct Vertex { pos: VertexPosition, tex_coords: TextureCoords }`), so I was confused by a few compiler errors that came up as a result. This clarifies those errors when processing the macro instead of leaving it up to rustc.
I'm new to contributing to OS projects/graphics programming, so I'm not sure if I'm missing anything. Thanks!!

Raise an error when a Vertex has fields of the same type.

---

luminance-derive/CHANGELOG.md
luminance-derive/Cargo.toml
luminance-derive/README.md
luminance-derive/src/lib.rs
luminance/README.md
luminance/src/lib.rs
luminance/tests/uniform_interface.rs
luminance/tests/vertex.rs

Moved the tests in `luminance/tests` and removed the dependency on
`luminance` from `luminance-derive`.
The tests are gated with `#![cfg(feature = "derive")]`.

Fix cyclic dep luminance <-> luminance-derive.

---

examples/common/src/funtest_483_indices_mut_corruption.rs
examples/common/src/lib.rs
examples/desktop/src/main.rs
examples/web/src/lib.rs
luminance-webgl/CHANGELOG.md
luminance-webgl/src/webgl2/buffer.rs

In the OpenGL 3.3 backend, there is an optimization that allows a
buffer object to be created and bound to a given target (for instance
`ARRAY_BUFFER`) and allows to rebind the buffer later to another
target (for instance `ELEMENT_ARRAY_BUFFER`). That optimization is handy
because it allows to dissociate data storage from data representation,
allowing to send a bunch of bytes and then using the target as source of
representation.
Well, turns out that optimization doesn’t work in WebGL2, so this commit
implements a way to keep track of what a buffer was created as and then
re-use that information every time we need to bind the buffer. That
should fix #483 (and probably other bugs no one has encountered yet).
Some integration tests are needed to ensure the fix does what it should.

Fix buffer target corruption in WebGL2 backend.

---

NEXT.md
examples/common/src/vertex_instancing.rs
luminance/src/tess.rs

The returned slice types were wrong and were using the `V` type
variable (the vertex type) instead of the `W` type (the instance type).

[luminance] Fix Tess::instances{,_mut}.

---

luminance/src/lib.rs

I found that the link to https://docs.rs/luminance/0.44.1/luminance/ to the examples where broken. This PR fixes it.

Updated link to examples in docs

---

examples/common/src/hello_world.rs
luminance-derive/src/semantics.rs
luminance-derive/src/vertex.rs

The fix provides a default, simple documentation for the generated
symbols so that code depending on it and compiled with
`#![deny(missing_docs)]` or even `#![forbid(missing_docs)]` will still
pass.
Fixes #446.

[luminance-derive] uminance-derive missing_docs.

---

luminance-gl/src/gl33/pipeline.rs
luminance-webgl/src/webgl2/pipeline.rs

`gl{Color,Depth,Stencil}Mask` applies to `glClear`, so make sure the depth mask if off when clearing the depth buffer.
Luminance does not currently use any other mask than `glDepthMask`, so this should be sufficient.

Fix clearing depth buffer when the previous pipeline set writes to off

---

luminance/src/backend/depth_stencil_slot.rs
luminance/src/backend/framebuffer.rs
luminance/src/framebuffer.rs
luminance/src/texture.rs

Also renamed one `depth_slot` variable for consistency, and made some minor rewordings.
This made comment lines longer — I rewrapped them to 100 characters (since rustfmt.toml specified that max length) even though the existing text in some files seemed wrapped to 120. Let me know if I should do something different.

Fix doc links to follow renaming `DepthSlot` to `DepthStencilSlot`.

---

examples/common/Cargo.toml

`DynamicImage::to_rgb8()` was added in 0.23.12, and `ImageBuffer::as_raw()` was added in 0.23.10, so the existing version specification of 0.23 was too old.
I noticed this because when I updated my old clone of the luminance repository, the examples failed to compile due to the existing lock file specifying an older `image` version.

[examples] Update `image` dependency to ^0.23.12.

---

luminance-derive/src/vertex.rs
luminance/src/tess.rs
luminance/src/vertex.rs

This was redundant as vec![_; HERE] doesn’t require `const` items (anymore?).

Remove Vertex::ATTR_COUNT.

---

luminance/src/lib.rs

Fix source link for luminance doc logo

---

examples/common/src/dynamic_uniform_interface.rs
examples/common/src/hello_world.rs
examples/common/src/hello_world_more.rs
examples/common/src/interactive_triangle.rs
examples/common/src/mrt.rs
examples/common/src/offscreen.rs
examples/common/src/query_texture_texels.rs
examples/common/src/render_state.rs
examples/common/src/shader_uniforms.rs
examples/common/src/skybox.rs
examples/common/src/sliced_vertex_entity.rs
examples/common/src/stencil.rs
examples/common/src/uni_buffer.rs
examples/common/src/vertex_instancing.rs
luminance-gl2/src/gl33.rs
luminance/src/backend.rs
luminance/src/context.rs
luminance/src/vertex_entity.rs
luminance/src/vertex_storage.rs

Instead of using VertexEntity<V, …, Interleaved<V>, …>, one can now use something like VertexEntity<V, …, Interleaving, …>. The way it works is by implementing a new trait, VertexStorageFamily, which has an associated type (type family) using a GAT:
type Storage<V>: AsVertexStorage<V>;

Use a type family and GAT to simplify vertex entity memory schemes.
