- examples/03-sliced-tess/src/main.rs
- examples/Cargo.toml
- src/pipeline.rs
- src/tess.rs
> Replace TessRender with TessSlice.

- src/pipeline.rs
> We now track framebuffer binding in the graphics state correctly.

- src/render_state.rs
> Disable face culling by default.

- src/texture.rs
> Enhance the documentation of texture types vs. GLSL sampler types.

- docs/design/luminance-1.0.md
[Rendered](https://github.com/phaazon/luminance-rs/blob/design/docs/design/luminance-1.0.md)
> Add luminance-1.0 design doc.

- luminance/src/tess.rs
The docs are great by the way. 👍
> Drive by typo fix!

- luminance/src/texture.rs
> Cubemaps have 2D faces

- luminance-examples/src/offscreen.rs
- luminance-examples/src/query-texture-texels.rs
- luminance/src/framebuffer.rs
> Add support of setting samplers when creating framebuffers.

- luminance/CHANGELOG.md
- luminance/src/pixel.rs
> Add sRGB pixel formats.

- luminance-examples/src/hello-world-glutin.rs
- luminance-glutin/CHANGELOG.md
- luminance-glutin/Cargo.toml
- luminance-glutin/src/lib.rs
This PR makes #249 overlap this feature set.
> Add GlutinSurface::from_builders.

- luminance-examples/src/displacement-map.rs
- luminance-examples/src/offscreen.rs
- luminance-examples/src/query-texture-texels.rs
- luminance-examples/src/texture.rs
- luminance-glutin/src/lib.rs
- luminance-windowing/src/lib.rs
- luminance/src/framebuffer.rs
- luminance/src/pipeline.rs
- luminance/src/texture.rs
This is a follow-up to #291.
This changes the API so it will require a point release bump.
> Remove Layering, Layerable and Flat types

- luminance/src/shader/program.rs
Let me know if this is what you had in mind for cleaning up ugly code. I believe this also fixes #299.
> Rewrite check_types_match with a macro_rules. #312

- luminance/src/framebuffer.rs
- luminance/src/pipeline.rs
> Convert Framebuffer into its slots

- luminance-examples/Cargo.toml
- luminance-examples/src/copy-multi-fs.glsl
- luminance-examples/src/multi-fs.glsl
- luminance-examples/src/multiple-targets.rs
- luminance/src/backend/color_slot.rs
Not actually solved! This is just my progress so far. I don't really know where to go from here though, it still seems to bind them all to the same location. I did notice a change in behavior at this commit 58fd8af8112f184ffacced2a92b59d25500f6b9b. Before this, both triangles in the example would be white, and after they are both colored.
> Fix framebuffers with multiple color slots

- luminance-webgl/src/webgl2/state.rs
During WebGL2State setup, enable the WebGL extensions `OES_texture_float_linear` and `EXT_color_buffer_float`.  These extensions allow the selection of the Linear options for MinFilter and MagFilter.
More details in #388.
> Enable WebGL extensions to support floating-point texture filtering #388

- luminance-examples/Cargo.toml
- luminance-examples/README.md
- luminance-examples/src/interactive-triangle.rs
> [luminance-examples] Add a new example to dynamically mutate vertices on the GPU.

- luminance-examples-web/src/lib.rs
"every field", singular, so "have" -> "has"
"sur" -> "sure"
> Fix grammar/typo in comment in WebGL example

- Cargo.toml
- integration-tests/README.md
- integration-tests/desktop/gl33-f64-uniform/Cargo.toml
- integration-tests/desktop/gl33-f64-uniform/src/main.rs
- luminance-examples/README.md
- luminance-gl/CHANGELOG.md
- luminance-gl/Cargo.toml
- luminance-gl/src/gl33/shader.rs
- luminance/CHANGELOG.md
- luminance/src/shader.rs
> Support f64 in shader (luminance-gl only so far)

- luminance-gl/src/gl33/buffer.rs
- luminance-gl/src/gl33/tess.rs
- luminance-webgl/src/webgl2/buffer.rs
- luminance-webgl/src/webgl2/tess.rs
> Fix incorrectly set mutable buffer slices. 

- luminance-webgl/CHANGELOG.md
- luminance-webgl/src/webgl2/state.rs
> [luminance-webgl] Allow to use several WebGL contexts.

- luminance-examples-web/index.js
- luminance-examples-web/src/lib.rs
- luminance-web-sys/CHANGELOG.md
- luminance-web-sys/src/lib.rs
> [luminance-web-sys, luminance-examples-web] Remove WindowOpt from WebSysWebGL2Surface::new.

- Cargo.toml
- integration-tests/web/Cargo.toml
- integration-tests/web/index.js
- integration-tests/web/package.json
- integration-tests/web/src/flatten_slice.rs
- integration-tests/web/src/fs.glsl
- integration-tests/web/src/lib.rs
- integration-tests/web/src/vs.glsl
- integration-tests/web/webpack.config.js
- luminance-webgl/src/slice.rs
- luminance-webgl/src/webgl2/shader.rs
> [luminance-webgl] Fix flatten_slice and WebGL uniform slice updates.

- integration-tests/desktop/src/main.rs
- integration-tests/desktop/src/segfault_drop_surface_surviving_gpu_resources.rs
> Add the desktop integration test segfault_drop_surface_surviving_gpu_resources.

- README.md
We at @katharostech use Luminance and love it! 😄
> Add Bevy Retro to Dependent Projects

- luminance-web-sys/src/lib.rs
I'm fairly certain I'm going to need this feature, but I marked it as a draft because I haven't tested it yet. I'll make it ready for review as soon as I test it. 😁
> Allow Creating WebGL Surface Directly From Canvas

- luminance-gl/src/gl33/buffer.rs
> Add null pointer check in OpenGL 3.3 buffer code.

- luminance/src/framebuffer.rs
> Enhance the documentation about Color / Depth slots.

- NEXT.md
- examples/common/src/funtest_483_indices_mut_corruption.rs
- luminance-front/src/tess.rs
- luminance-gl/src/gl33/buffer.rs
- luminance-gl/src/gl33/tess.rs
- luminance-webgl/src/webgl2/buffer.rs
- luminance-webgl/src/webgl2/tess.rs
- luminance/src/backend/tess.rs
- luminance/src/tess.rs
> Introduce lifetimes for slicing Tess.

- NEXT.md
- examples/common/src/displacement_map.rs
- examples/common/src/funtest_pixel_array_encoding.rs
- examples/common/src/shared.rs
- examples/common/src/skybox.rs
- luminance-gl/src/gl33/texture.rs
- luminance-webgl/src/webgl2/texture.rs
- luminance/src/backend/color_slot.rs
- luminance/src/backend/depth_stencil_slot.rs
- luminance/src/texture.rs
> Fix TexelUpload and memory reserve.

- examples/common/Cargo.toml
- examples/desktop/Cargo.toml
- examples/web/Cargo.toml
- luminance/Cargo.toml
> [luminance] luminance-0.47.
